
import {
  type Candidate,
  type Company,
  type CompanyJobOpening,
  WorkExperienceLevel,
  EducationLevel,
  LocationPreference,
  Availability,
  JobType,
  type DiaryPost,
} from './types';

export const mockCandidates: Candidate[] = [
  {
    id: 'cand1',
    name: 'Alice Wonderland',
    role: 'Senior Software Engineer',
    experienceSummary: '5 years of Python development, loves remote work and agile teams. Passionate about AI and machine learning applications. Proven track record of delivering high-quality code and leading project teams to success in fast-paced environments.',
    skills: ['Python', 'Django', 'React', 'AWS', 'Docker', 'AI', 'Machine Learning'],
    avatarUrl: 'https://placehold.co/500x700.png', // Taller image
    dataAiHint: 'professional woman',
    videoResumeUrl: 'https://storage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4', // Actual video URL placeholder
    profileStrength: 90,
    location: "San Francisco, CA",
    desiredWorkStyle: "Fully Remote, Flexible Hours",
    pastProjects: "Developed an e-commerce recommendation engine, Contributed to open-source ML library",
    // New fields
    workExperienceLevel: WorkExperienceLevel.SENIOR,
    educationLevel: EducationLevel.MASTER,
    locationPreference: LocationPreference.REMOTE,
    languages: ['English', 'German'],
    salaryExpectationMin: 120000,
    salaryExpectationMax: 160000,
    availability: Availability.ONE_MONTH,
    jobTypePreference: [JobType.FULL_TIME, JobType.CONTRACT],
  },
  {
    id: 'cand2',
    name: 'Bob The Builder',
    role: 'UX/UI Designer',
    experienceSummary: 'Creative designer with 3 years of experience in mobile and web application design. Proficient in Figma and Adobe Suite. User-centric approach with a strong portfolio of intuitive and visually appealing designs.',
    skills: ['UX Design', 'UI Design', 'Figma', 'Adobe XD', 'Prototyping', 'User Research'],
    avatarUrl: 'https://placehold.co/500x700.png',
    dataAiHint: 'creative man',
    profileStrength: 85,
    location: "New York, NY",
    desiredWorkStyle: "Hybrid, Collaborative Environment",
    pastProjects: "Redesigned a mobile banking app, Created a design system for a SaaS product",
    workExperienceLevel: WorkExperienceLevel.JUNIOR,
    educationLevel: EducationLevel.UNIVERSITY,
    locationPreference: LocationPreference.HYBRID,
    languages: ['English'],
    salaryExpectationMin: 70000,
    salaryExpectationMax: 90000,
    availability: Availability.IMMEDIATE,
    jobTypePreference: [JobType.FULL_TIME],
  },
  {
    id: 'cand3',
    name: 'Charlie Brown',
    role: 'Product Manager',
    experienceSummary: 'Results-driven PM with a knack for launching successful SaaS products. 7 years in product strategy and roadmap execution. Excellent communication and leadership skills, adept at cross-functional team collaboration.',
    skills: ['Product Management', 'Agile', 'Scrum', 'Roadmapping', 'Market Analysis', 'JIRA'],
    avatarUrl: 'https://placehold.co/500x700.png',
    dataAiHint: 'focused person',
    videoResumeUrl: 'https://storage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyrides.mp4',
    profileStrength: 95,
    location: "Austin, TX",
    desiredWorkStyle: "Remote or On-site, Fast-paced Startup",
    pastProjects: "Launched three new SaaS products from concept to market, Grew user base by 200% for a B2B platform",
    workExperienceLevel: WorkExperienceLevel.SENIOR,
    educationLevel: EducationLevel.UNIVERSITY,
    locationPreference: LocationPreference.SPECIFIC_CITY,
    languages: ['English', 'Spanish'],
    salaryExpectationMin: 130000,
    salaryExpectationMax: 170000,
    availability: Availability.NEGOTIABLE,
    jobTypePreference: [JobType.FULL_TIME],
  },
  {
    id: 'cand4',
    name: 'Diana Prince',
    role: 'Data Scientist',
    experienceSummary: 'Expert in statistical modeling and machine learning with 4 years experience. Eager to solve complex problems with data. Strong analytical abilities and experience with big data technologies.',
    skills: ['Machine Learning', 'Data Analysis', 'Python', 'R', 'SQL', 'TensorFlow'],
    avatarUrl: 'https://placehold.co/500x700.png',
    dataAiHint: 'intelligent woman',
    profileStrength: 88,
    location: "Boston, MA", // Changed from Remote for more variety
    desiredWorkStyle: "Remote, Research-Oriented",
    pastProjects: "Built a predictive model for customer churn, Optimized ad spend using ML algorithms",
    workExperienceLevel: WorkExperienceLevel.MID_LEVEL,
    educationLevel: EducationLevel.DOCTORATE,
    locationPreference: LocationPreference.REMOTE,
    languages: ['English', 'French'],
    salaryExpectationMin: 100000,
    salaryExpectationMax: 140000,
    availability: Availability.THREE_MONTHS,
    jobTypePreference: [JobType.FULL_TIME, JobType.CONSULTANT],
  },
  {
    id: 'cand5',
    name: 'Edward Scissorhands',
    role: 'Creative Director',
    experienceSummary: 'Visionary creative director with 12 years of experience in branding, advertising, and digital media. Known for innovative campaigns and artistic excellence.',
    skills: ['Branding', 'Art Direction', 'Campaign Strategy', 'Adobe Creative Suite', 'Team Leadership'],
    avatarUrl: 'https://placehold.co/500x700.png',
    dataAiHint: 'artistic director',
    videoResumeUrl: 'https://storage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4',
    profileStrength: 92,
    location: "Los Angeles, CA",
    desiredWorkStyle: "Creative agency, project-based work",
    pastProjects: "Led global rebranding for a major consumer product, Won multiple awards for advertising campaigns.",
    workExperienceLevel: WorkExperienceLevel.EXPERT,
    educationLevel: EducationLevel.MASTER,
    locationPreference: LocationPreference.SPECIFIC_CITY,
    languages: ['English'],
    salaryExpectationMin: 150000,
    salaryExpectationMax: 200000,
    availability: Availability.NEGOTIABLE,
    jobTypePreference: [JobType.FULL_TIME, JobType.CONSULTANT],
  },
];

const mockJobOpeningsComp1: CompanyJobOpening[] = [
  {
    title: "Senior Frontend Developer",
    description: "Join our team to build amazing user interfaces with React and Next.js. Experience with TypeScript is a plus. You'll be responsible for developing new features, maintaining existing code, and collaborating with backend developers.",
    salaryRange: '$120k - $160k',
    jobType: JobType.FULL_TIME,
    tags: ['frontend', 'react', 'nextjs', 'typescript'],
    location: "Remote (US)",
    requiredExperienceLevel: WorkExperienceLevel.SENIOR,
    requiredEducationLevel: EducationLevel.UNIVERSITY,
    workLocationType: LocationPreference.REMOTE,
    requiredLanguages: ['English'],
    salaryMin: 120000,
    salaryMax: 160000,
  },
  {
    title: "Backend Python Developer",
    description: "Help scale our infrastructure and build robust APIs using Python and Django. We are looking for someone with strong database skills and experience with cloud platforms like AWS.",
    salaryRange: '$110k - $150k',
    jobType: JobType.FULL_TIME,
    tags: ['backend', 'python', 'django', 'api', 'aws'],
    location: "Remote (Global)",
    requiredExperienceLevel: WorkExperienceLevel.MID_LEVEL,
    requiredEducationLevel: EducationLevel.UNIVERSITY,
    workLocationType: LocationPreference.REMOTE,
    requiredLanguages: ['English'],
    salaryMin: 110000,
    salaryMax: 150000,
  }
];

const mockJobOpeningsComp2: CompanyJobOpening[] = [
 {
    title: "Graphic Designer",
    description: "Create stunning visuals for various clients, including branding, web assets, and print materials. Proficiency in Adobe Creative Suite is required. A strong portfolio is a must.",
    salaryRange: '$70k - $90k',
    jobType: JobType.FULL_TIME,
    tags: ['design', 'graphic design', 'adobe suite', 'branding'],
    location: "New York, NY (Hybrid)",
    requiredExperienceLevel: WorkExperienceLevel.JUNIOR,
    requiredEducationLevel: EducationLevel.UNIVERSITY,
    workLocationType: LocationPreference.HYBRID,
    requiredLanguages: ['English'],
    salaryMin: 70000,
    salaryMax: 90000,
  },
  {
    title: "Social Media Manager",
    description: "Develop and execute social media strategies to grow our clients' online presence. Experience with content creation, analytics, and community management is key.",
    salaryRange: '$60k - $80k',
    jobType: JobType.PART_TIME,
    tags: ['social media', 'marketing', 'content creation', 'analytics'],
    location: "Remote (US)",
    requiredExperienceLevel: WorkExperienceLevel.JUNIOR,
    workLocationType: LocationPreference.REMOTE,
    requiredLanguages: ['English'],
    salaryMin: 60000,
    salaryMax: 80000,
  }
];
const mockJobOpeningsComp3: CompanyJobOpening[] = [
  {
    title: "Environmental Scientist",
    description: "Conduct research and develop solutions for environmental challenges. Requires a Master's degree in Environmental Science or related field and experience with data analysis.",
    salaryRange: '$90k - $130k',
    jobType: JobType.CONTRACT,
    tags: ['science', 'environment', 'research', 'sustainability'],
    location: "Various Project Sites",
    requiredExperienceLevel: WorkExperienceLevel.MID_LEVEL,
    requiredEducationLevel: EducationLevel.MASTER,
    workLocationType: LocationPreference.SPECIFIC_CITY, // Assuming project sites are specific
    requiredLanguages: ['English'],
    salaryMin: 90000,
    salaryMax: 130000,
  },
  {
    title: "Project Manager - Renewable Energy",
    description: "Lead exciting projects in the renewable energy sector. PMP certification and experience managing large-scale energy projects are preferred.",
    salaryRange: '$100k - $140k',
    jobType: JobType.FULL_TIME,
    tags: ['project management', 'renewable energy', 'pmp', 'leadership'],
    location: "Austin, TX",
    requiredExperienceLevel: WorkExperienceLevel.SENIOR,
    workLocationType: LocationPreference.SPECIFIC_CITY,
    requiredLanguages: ['English'],
    salaryMin: 100000,
    salaryMax: 140000,
  }
];

const mockJobOpeningsComp4: CompanyJobOpening[] = [
  {
    title: "Lead Game Developer (Unity)",
    description: "Spearhead the development of our next hit mobile game. Must have 5+ years of experience with Unity and C#, and a passion for creating engaging gameplay experiences.",
    salaryRange: "$130k - $170k",
    jobType: JobType.FULL_TIME,
    tags: ["gaming", "unity", "csharp", "mobiledev", "lead"],
    location: "Remote (Canada)",
    requiredExperienceLevel: WorkExperienceLevel.SENIOR,
    workLocationType: LocationPreference.REMOTE,
    requiredLanguages: ['English'],
    salaryMin: 130000,
    salaryMax: 170000,
  }
];

const mockJobOpeningsComp5: CompanyJobOpening[] = [
  {
    title: "Junior Marketing Analyst",
    description: "Support our marketing team with data analysis, campaign tracking, and report generation. Entry-level position, great for learning and growth. Basic SQL knowledge is a plus.",
    salaryRange: "$55k - $70k",
    jobType: JobType.FULL_TIME,
    tags: ["marketing", "analysis", "entrylevel", "data"],
    location: "Chicago, IL (Hybrid)",
    requiredExperienceLevel: WorkExperienceLevel.INTERN, // Or JUNIOR
    requiredEducationLevel: EducationLevel.UNIVERSITY,
    workLocationType: LocationPreference.HYBRID,
    requiredLanguages: ['English'],
    salaryMin: 55000,
    salaryMax: 70000,
  }
];


export const mockCompanies: Company[] = [
  {
    id: 'comp1',
    name: 'Innovatech Solutions',
    industry: 'Technology',
    description: 'Cutting-edge software solutions for a brighter future. We value innovation, collaboration, and impact. Join us to work on challenging projects with a talented team.',
    cultureHighlights: ['Remote-First', 'Unlimited PTO', 'Weekly Tech Talks', 'Health & Wellness'],
    logoUrl: 'https://placehold.co/500x350.png',
    dataAiHint: 'modern logo tech company',
    introVideoUrl: 'https://storage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4',
    companyNeeds: "We need to optimize our payment processing system and enhance user experience on our e-commerce platform.",
    jobOpenings: mockJobOpeningsComp1,
  },
  {
    id: 'comp2',
    name: 'Creative Spark Inc.',
    industry: 'Marketing & Advertising',
    description: 'We ignite brands with creative campaigns and data-driven strategies. Looking for passionate creators to join our vibrant and dynamic team.',
    cultureHighlights: ['Pet-Friendly Office', 'Flexible Hours', 'Creative Workshops', 'Team Outings'],
    logoUrl: 'https://placehold.co/500x350.png',
    dataAiHint: 'creative agency logo',
    companyNeeds: "We are looking to expand our design team to handle new client projects requiring innovative branding and digital experiences.",
    jobOpenings: mockJobOpeningsComp2,
  },
  {
    id: 'comp3',
    name: 'GreenFuture Ltd.',
    industry: 'Sustainability',
    description: 'Dedicated to building a sustainable future through innovative green technologies. Join our mission-driven team and make a real difference in the world.',
    cultureHighlights: ['Impactful Work', 'Collaborative Environment', 'Eco-Conscious', 'Learning Budget'],
    logoUrl: 'https://placehold.co/500x350.png',
    dataAiHint: 'eco friendly logo',
    introVideoUrl: 'https://storage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4',
    companyNeeds: "Seeking data scientists to analyze environmental data and improve our green tech solutions.",
    jobOpenings: mockJobOpeningsComp3,
  },
  {
    id: 'comp4',
    name: 'PixelPlay Studios',
    industry: 'Gaming',
    description: 'Creating immersive and fun gaming experiences for players worldwide. We are a team of passionate gamers and developers.',
    cultureHighlights: ['Game Nights', 'Latest Hardware', 'Flexible Work', 'Stock Options'],
    logoUrl: 'https://placehold.co/500x350.png',
    dataAiHint: 'gaming company logo controller',
    introVideoUrl: 'https://storage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4',
    companyNeeds: "We are looking for experienced game developers and artists to join our growing team for an exciting new IP.",
    jobOpenings: mockJobOpeningsComp4,
  },
  {
    id: 'comp5',
    name: 'MarketMinds Co.',
    industry: 'Market Research',
    description: 'Providing actionable insights through comprehensive market research and data analysis. Helping businesses make informed decisions.',
    cultureHighlights: ['Data-Driven', 'Continuous Learning', 'Client-Focused', 'Supportive Team'],
    logoUrl: 'https://placehold.co/500x350.png',
    dataAiHint: 'analytics chart logo',
    companyNeeds: "Expanding our team of analysts to cover new industries and research methodologies.",
    jobOpenings: mockJobOpeningsComp5,
  },
];

const additionalMockCompanies: Company[] = [
  {
    id: 'comp6',
    name: 'HealthFirst Diagnostics',
    industry: 'Healthcare Technology',
    description: 'Pioneering AI-driven diagnostic tools to improve patient outcomes. We are a fast-growing startup with a mission to revolutionize healthcare.',
    cultureHighlights: ['Impactful Work', 'Stock Options', 'Modern Tech Stack', 'Collaborative Research'],
    logoUrl: 'https://placehold.co/500x350.png',
    dataAiHint: 'healthcare tech logo',
    companyNeeds: "Looking for machine learning engineers and full-stack developers passionate about healthcare.",
    jobOpenings: [
      {
        title: "Machine Learning Engineer - Medical Imaging",
        description: "Develop and deploy ML models for analyzing medical images. PhD or MS in CS/EE preferred, with experience in Python, PyTorch/TensorFlow, and medical imaging standards.",
        salaryRange: "$140k - $180k",
        jobType: JobType.FULL_TIME,
        tags: ["ml", "ai", "medicalimaging", "python", "pytorch"],
        location: "Boston, MA (Hybrid)",
        requiredExperienceLevel: WorkExperienceLevel.SENIOR,
        requiredEducationLevel: EducationLevel.MASTER,
        workLocationType: LocationPreference.HYBRID,
        requiredLanguages: ['English'],
        salaryMin: 140000,
        salaryMax: 180000,
      },
    ],
  },
  {
    id: 'comp7',
    name: 'EduSphere Online',
    industry: 'EdTech',
    description: 'Providing accessible and engaging online learning platforms for K-12 and lifelong learners. Join us to shape the future of education.',
    cultureHighlights: ['Remote-First', 'Mission-Driven', 'Continuous Feedback', 'Professional Development'],
    logoUrl: 'https://placehold.co/500x350.png',
    dataAiHint: 'education online logo',
    companyNeeds: "Hiring instructional designers, full-stack developers, and customer success managers.",
    jobOpenings: [
      {
        title: "Instructional Designer",
        description: "Design and develop engaging online course content for various subjects. Experience with LMS platforms and curriculum development required.",
        salaryRange: "$75k - $95k",
        jobType: JobType.FULL_TIME,
        tags: ["edtech", "instructionaldesign", "curriculum", "lms"],
        location: "Remote (Global)",
        requiredExperienceLevel: WorkExperienceLevel.MID_LEVEL,
        requiredEducationLevel: EducationLevel.UNIVERSITY,
        workLocationType: LocationPreference.REMOTE,
        requiredLanguages: ['English'],
        salaryMin: 75000,
        salaryMax: 95000,
      },
    ],
  },
];

mockCompanies.push(...additionalMockCompanies.filter(ac => !mockCompanies.find(mc => mc.id === ac.id)));


export const mockDiaryPosts: DiaryPost[] = [
  {
    id: 'diary1',
    authorId: 'cand1',
    authorName: 'Alice Wonderland',
    authorAvatarUrl: 'https://placehold.co/100x100.png',
    dataAiHint: 'woman face',
    title: 'My First Week with a New AI Project!',
    content: 'Just wrapped up my first week diving deep into a new machine learning project. The learning curve is steep, but the potential impact is huge. Spent most of my time setting up the environment and preprocessing data. Already learned so much about TensorFlow Extended (TFX)! Excited for what\'s next. #AI #MachineLearning #NewBeginnings',
    imageUrl: 'https://placehold.co/600x400.png',
    timestamp: Date.now() - 1000 * 60 * 60 * 24 * 2, // 2 days ago
    tags: ['ai', 'learning', 'tensorflow'],
    likes: 15,
    views: 120,
    isFeatured: true,
  },
  {
    id: 'diary2',
    authorId: 'cand2',
    authorName: 'Bob The Builder',
    authorAvatarUrl: 'https://placehold.co/100x100.png',
    dataAiHint: 'man face',
    title: 'Brainstorming Session: Redesigning a Mobile App',
    content: 'Had an amazing brainstorming session with the team today for the new mobile app redesign. So many creative ideas flowing! We focused on user journey mapping and identifying pain points in the current app. Feeling inspired by the collaborative energy. #UXDesign #Teamwork #Creativity',
    timestamp: Date.now() - 1000 * 60 * 60 * 10, // 10 hours ago
    tags: ['ux', 'design', 'collaboration'],
    likes: 22,
    views: 95,
  },
  {
    id: 'diary3',
    authorId: 'cand1',
    authorName: 'Alice Wonderland',
    authorAvatarUrl: 'https://placehold.co/100x100.png',
    dataAiHint: 'woman face',
    title: 'Overcoming a Coding Challenge',
    content: 'Spent the entire day debugging a tricky Python script. It was frustrating, but that moment when you finally find the bug and everything works is just priceless! Persistence pays off. #Python #CodingLife #ProblemSolving',
    imageUrl: 'https://placehold.co/600x400.png',
    timestamp: Date.now() - 1000 * 60 * 60 * 24 * 5, // 5 days ago
    tags: ['python', 'debugging', 'development'],
    likes: 30,
    views: 250,
    isFeatured: true,
  },
  {
    id: 'diary4',
    authorId: 'cand3',
    authorName: 'Charlie Brown',
    authorAvatarUrl: 'https://placehold.co/100x100.png',
    dataAiHint: 'person face',
    title: 'Reflecting on Q3 Product Strategy',
    content: 'Just finished a deep dive into our Q3 product strategy. Lots of market research and data analysis involved. It\'s crucial to stay agile and adapt to customer needs. Feeling confident about the roadmap ahead. #ProductManagement #Strategy #SaaS',
    timestamp: Date.now() - 1000 * 60 * 30, // 30 minutes ago
    tags: ['product', 'strategy', 'planning'],
    likes: 8,
    views: 40,
  }
];
