
// swipehire-backend/DiaryPost.js
const mongoose = require('mongoose');

const DiaryCommentSchema = new mongoose.Schema({
    // _id is automatically generated by Mongoose for subdocuments
    userId: { // MongoDB _id of the User who made the comment
        type: mongoose.Schema.Types.ObjectId,
        ref: 'User',
        required: true,
    },
    userName: {
        type: String,
        required: true,
    },
    userAvatarUrl: {
        type: String,
        default: 'https://placehold.co/40x40.png', // Default placeholder
    },
    text: {
        type: String,
        required: true,
        trim: true,
        maxlength: 500,
    },
    timestamp: {
        type: Date,
        default: Date.now,
    }
}, { _id: true, timestamps: { createdAt: 'timestamp', updatedAt: false } }); // Use timestamp for createdAt

const DiaryPostSchema = new mongoose.Schema({
    title: {
        type: String,
        required: true,
        trim: true,
    },
    content: {
        type: String,
        required: true,
    },
    authorId: { // MongoDB _id of the User who created the post
        type: mongoose.Schema.Types.ObjectId,
        ref: 'User',
        required: true,
    },
    authorName: {
        type: String,
        required: true,
    },
    authorAvatarUrl: {
        type: String,
        default: 'https://placehold.co/100x100.png', // Default placeholder
    },
    imageUrl: {
        type: String,
        trim: true,
    },
    diaryImageHint: {
        type: String,
        trim: true,
    },
    tags: {
        type: [String],
        default: [],
    },
    likes: {
        type: Number,
        default: 0,
    },
    likedBy: { // Array of User MongoDB _ids who liked this post
        type: [mongoose.Schema.Types.ObjectId],
        ref: 'User',
        default: [],
    },
    views: {
        type: Number,
        default: 0,
    },
    commentsCount: {
        type: Number,
        default: 0,
    },
    comments: { 
        type: [DiaryCommentSchema],
        default: [],
    },
    isFeatured: {
        type: Boolean,
        default: false,
    },
    status: { // Added for content moderation
        type: String,
        enum: ['approved', 'pending_review', 'rejected'],
        default: 'approved',
    }
}, { timestamps: true }); // Enable timestamps for createdAt and updatedAt

module.exports = mongoose.model('DiaryPost', DiaryPostSchema);

    
