name = "swipehire-backend"
main = "index-optimized.mjs"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]

# Variables that can be set in the Cloudflare dashboard
[vars]
NODE_ENV = "production"
ENVIRONMENT = "workers"
FRONTEND_URL_PRIMARY = "https://swipehire.top"
FRONTEND_URL_SECONDARY = "https://www.swipehire.top"

# Secrets (set via wrangler secret put)
# Run these commands to set secrets:
# wrangler secret put MONGODB_URI
# wrangler secret put FORMSAPP_WEBHOOK_SECRET

# Route configuration
routes = [
  "swipehire-backend.swipehire.workers.dev/*"
]

# Note: CPU limits removed for free plan compatibility
# Note: Using .mjs extension for ES modules